language: cpp

env:
  - CPP="CC=gcc-4.9 && CXX=g++-4.9"
  - CPP="CC=gcc-5 && CXX=g++-5"
  - CPP="CC=gcc-6 && CXX=g++-6"
  - CPP="CC=gcc-7 && CXX=g++-7"
  - CPP="CC=clang-3.9 && CXX=clang++-3.9"
  - CPP="CC=clang-4.0 && CXX=clang++-4.0"
  - CPP="CC=clang-5.0 && CXX=clang++-5.0"
jobs:
  include:
    - stage: install
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-4.9
            - g++-5
            - g++-6
            - g++-7
            - clang-3.9
            - clang-4.0
            - clang-5.0
stages:
  - install
  - test
before_install:
  - eval "${CPP}"
before_script:
  - cat LICENSE | grep -q $(date +%Y) || echo "License doesn't cover $(date +%Y)"
script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - ./gtkmm_python_bindings
